### ISSUE TITLE
The number of Patches including cloud information

### ISSUE THREAD

**Issue by whxueChris** [SorourMo/95-Cloud-An-Extension-to-38-Cloud-Dataset#3]
Hi! thanks for your work,  Could you provide the number of the image patches including cloud information? Some image patches don't include cloud, although they are not originally located in the black margins around the Landsat 8 images.

**Comment by SorourMo** [comment]
Hi @xwhkkk,
Thanks for your question. In the 38-Cloud dataset, there are 5155 non-empty (non-backfilled) "training" patches, 649 of which don't have any cloud pixels. Those numbers are 21502 and 4738 in the 95-Cloud dataset, respectively.
Those numbers are just for training sets. I don't have exact numbers for the test sets and/or the training+test sets.
